# -*- coding: utf-8 -*-
"""LazyPredict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLiqWc4s6JxnV2fkivnkt7Yrajh4aLdI
"""

pip install lazypredict

import lazypredict

from lazypredict.Supervised import LazyClassifier , LazyRegressor
from sklearn import datasets
from sklearn.utils import shuffle
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

diabetes  = datasets.load_diabetes()

type(diabetes)

diabetes.DESCR

diabetes["DESCR"]

diabetes.data

print(diabetes.keys())
print(diabetes.DESCR)

diabetes.target

X , y = shuffle(diabetes.data , diabetes.target , random_state = 42)

X = X.astype(np.float32)

offset =  int (X.shape[0] * 0.9)

X_train , y_train = X[:offset] , y[:offset]
X_test , y_test = X[offset:] , y[offset:]

X_train

X[0]

y[0]

reg = LazyRegressor(verbose = 0 , ignore_warnings = True , custom_metric =None)

models , predictions = reg.fit(X_train , X_test , y_train , y_test)

print(models)

